name: Restrict Merge to Main
on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]  # Runs on PR updates too

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check source branch
        run: |
          echo "Source branch: ${{ github.head_ref }}"
          echo "Target branch: ${{ github.base_ref }}"
          
          if [[ "${{ github.head_ref }}" != "dev" ]]; then
            echo "❌ ERROR: Only pull requests from 'dev' branch can be merged into main."
            echo "Current source branch: ${{ github.head_ref }}"
            echo "Please merge your changes to 'dev' first, then create a PR from dev to main."
            exit 1
          fi
          
          echo "✅ SUCCESS: Valid source branch 'dev' detected."
